# .github/workflows/macos-test.yml

name: Cross-Platform Backend Startup Test

on:
  push:
    branches: [ "development", "feature/**" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  build-and-test-on-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source_code/backend/requirements.txt
      - name: Create api_keys.txt from secret
        if: ${{ secrets.GEMINI_API_KEY != ''}}
        run: |
          echo "CI_KEY,${{ secrets.GEMINI_API_KEY }}" > source_code/backend/api_keys.txt
      - name: Run backend script for a short time to check for startup errors
        run: |
          echo "Attempting to start backend.py in the background..."
          python source_code/backend/backend.py &
          PID=$!
          sleep 5
          if kill -0 $PID 2>/dev/null; then
            echo "SUCCESS: The backend process is still running after 5 seconds."
            kill $PID
          else
            echo "FAILURE: The backend process crashed on startup."
            exit 1
          fi

  build-and-test-on-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source_code/backend/requirements.txt
      - name: Create api_keys.txt from secret
        if: ${{ secrets.GEMINI_API_KEY != '' }}
        run: |
          echo "CI_KEY,${{ secrets.GEMINI_API_KEY }}" > source_code/backend/api_keys.txt
      - name: Run backend script for a short time to check for startup errors
        run: |
          echo "Attempting to start backend.py in the background..."
          python source_code/backend/backend.py &
          PID=$!
          sleep 5
          if kill -0 $PID 2>/dev/null; then
            echo "SUCCESS: The backend process is still running after 5 seconds."
            kill $PID
          else
            echo "FAILURE: The backend process crashed on startup."
            exit 1
          fi